version: "3.1"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - gobarber_db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=gobarber

  gobarber_db:
    image: postgres
    container_name: gobarber
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432